import { _electron } from 'playwright'
const app = await _electron.launch({ args: ['out/main/index.js'] })
const win = await app.firstWindow()
await win.waitForSelector('.brand', { timeout: 15000 })
await win.waitForTimeout(800)
await win.click('.nav button:has-text("Erweitert")')
await win.click('.nav button:has-text("Marketplace")')
await win.waitForTimeout(600)
await win.screenshot({ path: 'C:/Users/Maurice/AppData/Local/Temp/dc-shots/10-marketplace.png' })
await app.close()
console.log('ok')
